name: CI

on: workflow_dispatch

jobs:
    date_on_linux:
        runs-on: ubuntu-latest
        steps:
            - name: Run a multi-line script
              run: |
                  echo Date on linux
                  date1
    date_on_windows:
        runs-on: windows-latest
        # 加入 if 和 needs，if 绑定条件、needs 绑定 job的name
        if: ${{ success() }}
        # 依赖多个jobs时可以写成 needs: [job1,job2]
        needs: date_on_linux
        steps:
            - name: Run a multi-line script
              run: |
                  echo "Date on Windows"
                  Get-Date

