name: CI

on: workflow_dispatch

jobs:
  echo_on_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, World!

      - name: Run a multi-line script
        run: 
          echo first scrpit,
          echo second scrpit.
          date
