name: CI

on: workflow_dispatch

jobs:
    date_on_linux:
        runs-on: ubuntu-latest
        steps:
            - name: Run a multi-line script
              run: |
                  echo Date on linux
                  date
    date_on_windows:
        runs-on: windows-latest
        steps:
            - name: Run a multi-line script
              run: |
                  echo "Date on Windows"
                  Get-Date

